steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west8-docker.pkg.dev/projekti-nodemailer/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west8-docker.pkg.dev/projekti-nodemailer/reservations/production',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west8-docker.pkg.dev/projekti-nodemailer/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west8-docker.pkg.dev/projekti-nodemailer/auth/production',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west8-docker.pkg.dev/projekti-nodemailer/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west8-docker.pkg.dev/projekti-nodemailer/notifications/production',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west8-docker.pkg.dev/projekti-nodemailer/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'europe-west8-docker.pkg.dev/projekti-nodemailer/payments/production',
      ]
